name: ckb-vm-bench-scripts

on:
  push:
    branches: [ main ]
    paths: "ckb-vm-bench-scripts/**"
  pull_request:
    branches: [ main ]
    paths: "ckb-vm-bench-scripts/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: |
        clang --version
        sudo ln -s $(which llvm-ar-18) /usr/bin/llvm-ar || true
        sudo ln -s $(which llvm-objcopy-18) /usr/bin/llvm-objcopy || true
        rustup target add riscv64imac-unknown-none-elf
        cargo install ckb-debugger
    - name: Build
      run: |
        cd ckb-vm-bench-scripts
        make build
        make report >> report.txt
    - uses: actions/upload-artifact@v4
      with:
        name: ckb-vm-bench-scripts-report.txt
        path: ckb-vm-bench-scripts/report.txt
